<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/10 21:45:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jbeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
