<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/25 05:42:48
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 5,
  'app_max_jobs_on_category' => 10,
));
