<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/10 22:12:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_tmp',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
